// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbmYc8MPIpq3PVDjMFmn56nX3P-WjwFPU',
    appId: '1:986633581175:web:c7465d7e256c778bd0cc72',
    messagingSenderId: '986633581175',
    projectId: 'thai-story-ai',
    authDomain: 'thai-story-ai.firebaseapp.com',
    storageBucket: 'thai-story-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7vFrU1QieJOZR8KKt7_uw2n8bgqOFXyM',
    appId: '1:986633581175:android:c988c12c20bc7f3bd0cc72',
    messagingSenderId: '986633581175',
    projectId: 'thai-story-ai',
    storageBucket: 'thai-story-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGqRqEhSNxKHoLTZ__h0PBnUSpnDMugw',
    appId: '1:986633581175:ios:56d92363d3873c0cd0cc72',
    messagingSenderId: '986633581175',
    projectId: 'thai-story-ai',
    storageBucket: 'thai-story-ai.firebasestorage.app',
    iosBundleId: 'com.example.thaiStoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOGqRqEhSNxKHoLTZ__h0PBnUSpnDMugw',
    appId: '1:986633581175:ios:56d92363d3873c0cd0cc72',
    messagingSenderId: '986633581175',
    projectId: 'thai-story-ai',
    storageBucket: 'thai-story-ai.firebasestorage.app',
    iosBundleId: 'com.example.thaiStoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbmYc8MPIpq3PVDjMFmn56nX3P-WjwFPU',
    appId: '1:986633581175:web:e8ee3618d5b4a659d0cc72',
    messagingSenderId: '986633581175',
    projectId: 'thai-story-ai',
    authDomain: 'thai-story-ai.firebaseapp.com',
    storageBucket: 'thai-story-ai.firebasestorage.app',
  );
}
